# Generated by Django 4.2.9 on 2024-01-29 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_remove_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='price',
        ),
    ]
